### ISSUE TITLE
"Percent" value

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#103]
If I would want to implement "percent" as a value for dimensions, where would I go to define it? And how should it be written in the LaTeX input (obviously we can't use `80%`)?

I would like to have to option to use percent for
* `line-width`
* protrusion (use up to 60% of the available margin)
* `staffsize` (80% of the default size)

**Comment by jperon** [comment]
I think you could:
- use `80\%`, which is quite intuitive for someone who would know LaTeX well;
- update `ly.is_dim` so that it accepts it;
- define a new local function `convert_percent(percentage, dimension)` that would return `dimension * percentage / 100`;
- add necessary calculations in `Score:calc_properties`.

Just an idea.

**Comment by rpspringuel** [comment]
The LaTeX way of representing a percentage of a given length is to write a floating point number followed by the length.  So 80% of the line width would be `0.8\linewidth`.  Is there something wrong with that sort of notation?

This could be applied to protrusion if the appropriate distance is defined. 

Staffsize, IIRC, is a number, not a length, but perhaps the count registers can be used in the same way (I haven't checked). 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ
