### ISSUE TITLE
Can we ignore "irrelevant" options?

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#114]
https://github.com/jperon/lyluatex/projects/1#column-2040071 lists options as "irrelevant" because they are only needed for texinfo output.

I think we should provide a uniform way to issue a warning when any of those options is used in a (previously lilypond-book) document. That should be different from the usual LaTeX error when an unknown package option is used.

**Comment by jperon** [comment]
For sure, we should ignore them. To issue a warning, we could use the `info()` function.

**Comment by rpspringuel** [comment]
I think the version one might still be useful, but the others are probably safe to ignore (with an appropriate message). 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by jperon** [comment]
Which version should be added ? The version of the fragment (if specified), the version of `lilypond` which was used to compile it, or a custom version given by the user ?

**Comment by rpspringuel** [comment]
If I read the lilypond-book specification correctly, its the version of `lilypond` which was used to compile the code.  Presumably when a user wants this option, their code (fragment) does not have an explicit version statement and they're using the option so that the final document does (to make it easier on the reader to tell what version of LilyPond produces the shown result).
