### ISSUE TITLE
Accept non-relative paths for \lilypondfile

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#63]
Currently the file to be included by `\lilypondfile` is searched for

* as a relative path appended to `CURRFILEDIR`
* using `kpse.find_file()`

I'm not sure about the latter, but I assume it finds the files that LaTeX can find.

In addition it should be possible to find files as
* absolute paths
* paths that are relative to any of the given include paths

**Comment by jperon** [comment]
Just fixed. Lyluatex looks for input file following this order:
- the file "as is", so that absolute paths work;
- relative to `CURRFILEDIR`;
- relative to `includepaths`, following the order of their definition;
- using `kpse.find_file()` (which you understood well).

**Comment by uliska** [comment]
:+1

**Comment by jperon** [comment]
I've just pushed another modification: now, the file relative to `CURRFILEDIR` is searched before the file "as is", because:
- if the given path is absolute, it won't match anyway with `CURRFILEDIR`, so this doesn't change anything;
- if the given path is relative, a file within the main directory would have had precedence over files relative to the directory of an included tex file, which could have given (in fairly rare cases…) unexpected results.
