### ISSUE TITLE
noindent

### ISSUE THREAD

**Issue by jperon** [jperon/lyluatex#72]
Set indentation of the first music system to zero. This option affects LilyPond, not the text layout. Since no indentation is the default, `noindent` is redundant normally.

**Comment by jperon** [comment]
Shouldn't this be considered as done too ?

**Comment by rpspringuel** [comment]
Only insomuch as it's the current no-op option.  The reason I didn't mark it as done is because it needs to be kept in mind as https://github.com/jperon/lyluatex/projects/1#card-6793031 is implemented.  

The pertinent line in the code is [334 in lyluatex.lua](https://github.com/jperon/lyluatex/blob/1b93149ab3b315e20b3e019fc6f25e2c64b563f0/lyluatex.lua#L334).  Right now it always sets the indent to 0 and thus this option is redundant.  Howeveer, when the `indent` option is implemented, then this will change.  If `indent` is set globally, then `noindent` should be the equivalent of `indent=0pt` as a local option.  Likewise, `noindent` as the global rule should be the same as `indent=0pt` and should be overridden by a local `indent=...`.  If both `indent` and `noindent` are given at the local level we should probably raise at least a warning, if not an outright error, because the options are conflicting.
