### ISSUE TITLE
lyluatex seems to have problems with directory names containing spaces

### ISSUE THREAD

**Issue by mhohl** [jperon/lyluatex#8]
Hello,

my latest project based on lyluatex worked fine, but as soon as I renamed the directory where the .tex file  was located, some cryptic errors occured – it looks as if lyluatex does not work correctly in directories containing spaces in its name (I am working under Ubuntu 14.04 LTS).

Greetings,
Marc

**Comment by rpspringuel** [comment]
TeX (not just lyluatex) generally doesn't like spaces in file names.  This usually doesn't effect containing folders, however, so long as relative file references are being used.  If you have absolute references that might be a problem.  Without knowing more about your project structure (what files are located where) and how you reference them, though, it's impossible to know exactly what the problem is.  Can you provide some more details?

**Comment by mhohl** [comment]
Am 03.12.2015 um 04:44 schrieb Br. Samuel Springuel:
> TeX (not just lyluatex) generally doesn't like spaces in file names.
> This usually doesn't effect containing folders, however, so long as
> relative file references are being used. If you have absolute references
> that might be a problem. Without knowing more about your project
> structure (what files are located where) and how you reference them,
> though, it's impossible to know exactly what the problem is. Can you
> provide some more details?

After trying to create a minimal example, I think I found the culprit:
I use a wrapper for the lilypond call that stumbles upon the spaces, so
this seems not to be a problem of lyluatex itself.

Sorry for the noise.

Marc
